# Generated by Django 3.2.6 on 2021-10-09 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código de la Categoría')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(verbose_name='Texto descriptivo de la Categoría')),
                ('activo', models.CharField(choices=[('Si', 'Activo'), ('No', 'Inactivo')], default='Si', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('tipo_doc', models.CharField(choices=[('Cc', 'Cédula'), ('Pa', 'Pasaporte'), ('Ce', 'Cédula Extranjería')], default='Cc', max_length=2, verbose_name='Tipo Doc. Identificación')),
                ('doc_identificacion', models.CharField(max_length=15, verbose_name='Documento Identificación')),
                ('dir_envio', models.CharField(max_length=100, verbose_name='Dirección de Envio')),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('activo', models.CharField(choices=[('Si', 'Activo'), ('No', 'Inactivo')], default='Si', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(default=datetime.date.today)),
                ('forma_pago', models.CharField(choices=[('PSE', 'PSE'), ('Tj', 'Tarjeta Crédito'), ('Py', 'Paypal'), ('Mp', 'Mercado Pago')], default='PSE', max_length=3)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('Rg', 'Registrado'), ('Pr', 'En preparación'), ('En', 'Enviado'), ('Re', 'Recibio Cliente'), ('Fn', 'Finalizado sin reclamaciones'), ('Fr', 'Finalizado con reclamaciones'), ('Ca', 'Cancelado')], default='Rg', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código del producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Texto descriptivo del producto')),
                ('unidad', models.CharField(choices=[('Kg', 'Kilogramo'), ('Lb', 'Libra'), ('Un', 'Unidad'), ('Pa', 'Paquete')], default='Kg', max_length=2)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_precio', models.DateField(default=datetime.date.today)),
                ('activo', models.CharField(choices=[('Si', 'Activo'), ('No', 'Inactivo')], default='Si', max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.categorias')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.productos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(choices=[('CeB', 'Bodega Centro Cr 3b 12-23 Bog'), ('SuB', 'Bodega Sur calle 34c 14-13 Bog'), ('NoB', 'Bodega Norte Calle 80 64-23 Bog')], default='NoB', max_length=3)),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(choices=[('1', '[1] Estrella'), ('2', '[2] Estrella'), ('3', '[3] Estrella'), ('4', '[4] Estrella'), ('5', '[5] Estrella')], default='5', max_length=1)),
                ('fecha_calificacion', models.DateField(default=datetime.date.today)),
                ('comentario', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendavirtualapp.clientes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendavirtualapp.productos')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
