# Generated by Django 3.2.6 on 2021-10-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtualapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
