# Generated by Django 3.2.6 on 2021-10-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtualapp', '0002_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default=231, max_length=15, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
