# Generated by Django 3.2.6 on 2021-10-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtualapp', '0003_clientes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.clientes'),
            preserve_default=False,
        ),
    ]
