# Generated by Django 3.2.6 on 2021-09-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('tipo', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.IntegerField()),
                ('valor_renta', models.IntegerField()),
            ],
        ),
    ]
